name: LogS-model-API
channels:
  - conda-forge
dependencies:
  # API
  - fastapi=0.99.0
  - uvicorn=0.22.0
  # Dev
  - black
  - ipykernel
  - mypy
  - ruff
  # Test
  - httpx
  - pytest
  # Model
  - datamol=0.9.2
  - molfeat=0.8.6
  - numpy=1.24.2
  - pandas=1.5.3
  - python=3.10
  - rdkit=2023.3.2
  - scikit-learn=1.2.2
  